# .github/workflows/imagepush.yml
name: Docker Image Build and Push

on:
 workflow_call:

jobs:
  image_push:
    runs-on: self-hosted
    env:
      DOCKER_IMAGE: vishalgore944/petapp:${{ github.sha }}

    steps:
      - name: Build Docker Image
        run: |
          sudo docker build -t ${{ env.DOCKER_IMAGE }} .
          sudo docker save ${{ env.DOCKER_IMAGE }} > docker_image.tar


      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: sudo docker push ${{ env.DOCKER_IMAGE }}
