# .github/workflows/sonar.yml
name: Sonar Scan

on:
 workflow_call:

jobs:
  sonar:
    runs-on: self-hosted
    #needs: build  # Ensures Sonar runs after build succeeds
    steps:
      - name: SonarCloud Scan
        run: mvn sonar:sonar -Dsonar.projectKey=vishalgore944_DevSecops_Pipeline -Dsonar.organization=vishalgore944 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=cd2067bc8e78cad94ab348acc0f2a06d252fc3fa
